version: '3.8'

services:
  web-app:
    image: node:16
    container_name: node_app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: node server.js
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-sql
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin123#
      MYSQL_DATABASE: request_management
    networks:
      - app-network

networks:
  app-network:
    driver: bridge